---
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{rg_name}}"
      name: "{{nsg_name}}"
      rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: WEB
        protocol: Tcp
        destination_port_range:
         - 80
         - 443
        access: Allow
        priority: 1002
    register: netsg
  - debug:
        var: netsg
