---
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{rg_name}}"
      name: "{{vnet_name}}"
      address_prefixes: "{{vnet_addr}}"
    register: vnet
  - debug:
      var: vnet
